name       : haskell-lens
version    : 4.15.1
release    : 1
source     :
    - https://hackage.haskell.org/package/lens-4.15.1/lens-4.15.1.tar.gz : 5cfaa64cb1b9787193c2247a1ed1c248104ba5fadb91cec6432e648e41b1bea6
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides families of lenses, isomorphisms, folds, traversals, getters and setters.
description: |
    This package provides families of lenses, isomorphisms, folds, traversals, getters and setters.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-kan-extensions
    - haskell-parallel
    - haskell-reflection
    - haskell-unordered-containers
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
