name       : haskell-lens
version    : 4.16.1
release    : 2
source     :
    - http://hackage.haskell.org/package/lens-4.16.1/lens-4.16.1.tar.gz : f5bec97b1d5cf3d6487afebc79b927bd5a18f1fd594b104de36a35bf606ea4c6
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides families of lenses, isomorphisms, folds, traversals, getters and setters.
description: |
    This package provides families of lenses, isomorphisms, folds, traversals, getters and setters.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-call-stack
    - haskell-kan-extensions
    - haskell-parallel
    - haskell-reflection
    - haskell-unordered-containers
    - haskell-vector
setup      : |
    sed -i "s|Custom|Simple|" lens.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
