name       : haskell-lens
version    : 4.19.2
release    : 3
source     :
    - https://hackage.haskell.org/package/lens-4.19.2/lens-4.19.2.tar.gz : 52f858ae3971a5104cdba5e81a27d154fda11fe65a54a4ac328c85904bdec23b
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides families of lenses, isomorphisms, folds, traversals, getters and setters.
description: |
    This package provides families of lenses, isomorphisms, folds, traversals, getters and setters.
builddeps  :
    - haskell-cabal-install
    - haskell-call-stack-devel
    - haskell-kan-extensions-devel
    - haskell-parallel-devel
    - haskell-reflection-devel
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-call-stack-devel
        - haskell-kan-extensions-devel
        - haskell-parallel-devel
        - haskell-reflection-devel
        - haskell-vector-devel
networking : yes
setup      : |
    sed -i "s|Custom|Simple|" lens.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
